/**
 * Tutorial #1 - AI Video Pipeline (video-flow)
 *
 * "Why 80% of Corporate Videos Never Get Published (And How AI Fixes It)"
 *
 * 15 minutes @ 30fps = 27,000 frames
 *
 * Voiceover: generated by video-flow/local/video-production/generate-voiceover.py
 * Voice: Linda Mohamed (ElevenLabs ID: ttn4VvmCIm5phDs4dj5o)
 *
 * Background footage: served via Flask media proxy at localhost:5002
 * or drop reinvent-netapp.mp4 into this project's public/ folder.
 */

import React from "react";
import type { TutorialSpec } from "../YouTubeTutorial";
import { YouTubeTutorial } from "../YouTubeTutorial";

const SPEC: TutorialSpec = {
  project_name: "AI Video Pipeline",
  partner:  { name: "NetApp", color: "#0072CE" },
  co_brand: { name: "AWS",    color: "#FF9900" },

  hook_stats: [
    { value: "250 videos", label: "filmed at re:Invent 2025", color: "#F1F5F9" },
    { value: "47 min",     label: "to a finished, tagged edit",  color: "#4ADE80" },
    { value: "€0.42",      label: "total pipeline cost",         color: "#4ADE80" },
  ],

  voiceover_src: "", // voiceover disabled - file not available

  chapters: [
    {
      id: 0,
      name: "hook",
      number: "",
      title: "",
      start_sec: 0,
      end_sec: 45,
      bg: "video",
      video_src: "reinvent-netapp.mp4",
      content: { type: "blank" },
    },
    {
      id: 1,
      name: "problem",
      number: "01",
      title: "Why Videos Never Get Published",
      start_sec: 45,
      end_sec: 150,
      content: {
        type: "stats",
        data: {
          stats: [
            { value: "1 in 5",  label: "corporate video projects published on time",   source: "Wyzowl Video Marketing Report" },
            { value: "40–60h",  label: "post-production per 1h interview",             source: "Industry standard", color: "#F87171" },
            { value: "68%",     label: "of businesses report video production bottlenecks", source: "Wyzowl 2024", color: "#FF9900" },
          ],
        },
      },
    },
    {
      id: 2,
      name: "scale",
      number: "02",
      title: "The Scale of the Problem",
      start_sec: 150,
      end_sec: 270,
      content: {
        type: "stats",
        data: {
          stats: [
            { value: "$50B",  label: "global video production market",      source: "Industry analysis" },
            { value: "82%",   label: "of internet traffic is video by 2025", source: "Cisco Annual Internet Report", color: "#FF9900" },
            { value: "75%",   label: "of enterprise data is unstructured on-prem NAS", source: "IDC", color: "#0072CE" },
          ],
        },
      },
    },
    {
      id: 3,
      name: "cloud-solution",
      number: "03",
      title: "The Cloud-Native Solution",
      start_sec: 270,
      end_sec: 360,
      content: {
        type: "list",
        data: {
          items: [
            { icon: "arrow-up", title: "Path 1: Automated", desc: "Upload → EventBridge → Step Functions → AI output. Zero human involvement.", color: "#4ADE80" },
            { icon: "chat", title: "Path 2: Prompt-Driven", desc: '"Find clips from Vienna mentioning pricing" → AI searches archive → assembles edit.', color: "#FF9900" },
            { icon: "warning", title: "The Catch", desc: "Enterprise data doesn't start on S3. Petabyte migration is not an option.", color: "#F87171" },
          ],
        },
      },
    },
    {
      id: 4,
      name: "enterprise",
      number: "04",
      title: "Where Enterprise Data Actually Lives",
      start_sec: 360,
      end_sec: 450,
      content: {
        type: "list",
        data: {
          items: [
            { icon: "dollar", title: "Migration costs a fortune", desc: "Petabyte-scale data movement: $0.09/GB × hundreds of TB", color: "#F87171" },
            { icon: "lock", title: "Compliance blocks migration", desc: "GDPR, HIPAA, data sovereignty - data must stay on-prem", color: "#F87171" },
            { icon: "warning", title: "Operational disruption", desc: "You cannot pause a broadcaster's archive for 18 months", color: "#F87171" },
          ],
        },
      },
    },
    {
      id: 5,
      name: "bridge",
      number: "05",
      title: "The Bridge: FSxN + S3 Access Points",
      start_sec: 450,
      end_sec: 540,
      content: {
        type: "stats",
        data: {
          stats: [
            { value: "$0",     label: "migration cost - data never moves",    color: "#4ADE80" },
            { value: "0",      label: "lines of ML training code required",   color: "#FF9900" },
            { value: "€0.50",  label: "per video processed end-to-end",       color: "#0072CE" },
          ],
        },
      },
    },
    {
      id: 6,
      name: "pipeline",
      number: "06",
      title: "Inside the Pipeline",
      start_sec: 540,
      end_sec: 660,
      content: {
        type: "list",
        data: {
          items: [
            { icon: "gear", title: "Pre-Processing",     desc: "File Sanitizer + Metadata Extractor + proxy creation", color: "#A78BFA" },
            { icon: "target", title: "Parallel AI Analysis", desc: "Rekognition (visual) + Transcribe (audio) + custom vocabulary", color: "#FF9900" },
            { icon: "layers", title: "8-Agent Film Crew",   desc: "Director · Editor · Fact Checker · Pacing Analyst - all deliberating", color: "#0072CE" },
            { icon: "film", title: "MediaConvert Output", desc: "16:9 YouTube · 9:16 Instagram · 1:1 LinkedIn - all in one run", color: "#4ADE80" },
          ],
        },
      },
    },
    {
      id: 7,
      name: "demo",
      number: "07",
      title: "Live Demo - re:Invent 2025",
      start_sec: 660,
      end_sec: 750,
      bg: "video",
      video_src: "reinvent-netapp.mp4",
      content: { type: "blank" },
    },
    {
      id: 8,
      name: "industries",
      number: "08",
      title: "Industry Use Cases",
      start_sec: 750,
      end_sec: 810,
      content: {
        type: "list",
        data: {
          items: [
            { icon: "globe", title: "Broadcast & Media",     desc: "Decades of archive footage - suddenly searchable & monetizable", color: "#FF9900" },
            { icon: "layers", title: "Enterprise Comms",      desc: "Training, testimonials, all-hands - published in hours not weeks", color: "#0072CE" },
            { icon: "star", title: "Event Videography",     desc: "Highlight reel delivered before the client unpacks", color: "#F472B6" },
            { icon: "shield", title: "Healthcare & Education", desc: "HIPAA-compliant, AI-indexed, data sovereignty preserved", color: "#4ADE80" },
          ],
        },
      },
    },
    {
      id: 9,
      name: "economics",
      number: "09",
      title: "The Economics - Scales to Zero",
      start_sec: 810,
      end_sec: 870,
      content: {
        type: "comparison",
        data: {
          headline: "You are not training a model. AWS trained it.",
          rows: [
            { label: "Train your own model",  value: "$500K–5M", unit: "one-time compute + data",       color: "#F87171" },
            { label: "Hire a video editor",   value: "$45K–90K", unit: "per year, ~200 videos/month",   color: "#FF9900" },
            { label: "This pipeline",         value: "€0.50",    unit: "per video · 200 in 90 min",     color: "#4ADE80", highlight: true },
          ],
        },
      },
    },
    {
      id: 10,
      name: "outro",
      number: "",
      title: "",
      start_sec: 870,
      end_sec: 900,
      bg: "video",
      video_src: "reinvent-netapp.mp4",
      content: { type: "blank" },
    },
  ],

  outro: {
    tagline: "Your data stays on NetApp.\nYour innovation runs on AWS.",
    sub: "One S3 Access Point. Three pretrained models. Zero migration.",
    presenter: "Linda Mohamed - AWS Hero · NetApp Partner",
  },
};

export const VideoFlowPipelineTutorial: React.FC = () => (
  <YouTubeTutorial spec={SPEC} layout="cinematic" />
);
