#!/usr/bin/env python3
"""
Generate template variants from configuration.

This script generates:
1. Showcase component files (e.g., ListicleShowcase.tsx)
2. Root.tsx imports and composition registrations
3. templates.json variant entries

Usage:
  python scripts/generate-template-variants.py --template listicle
  python scripts/generate-template-variants.py --all
  python scripts/generate-template-variants.py --template listicle --dry-run
  python scripts/generate-template-variants.py --template listicle --output showcase
  python scripts/generate-template-variants.py --template listicle --output root
  python scripts/generate-template-variants.py --template listicle --output json
"""

import argparse
import json
import os
import sys
from pathlib import Path

# Load configuration
CONFIG_PATH = Path(__file__).parent / "template-config.json"

def load_config():
    with open(CONFIG_PATH) as f:
        return json.load(f)

def get_all_themes(config):
    """Get flat list of all theme names."""
    themes = []
    for group in ["original", "extended", "european", "flat", "canva"]:
        themes.extend(config["themes"][group])
    return themes

def pascal_case(s):
    """Convert to PascalCase: 'dark' -> 'Dark', 'materialBlue' -> 'MaterialBlue'"""
    if not s:
        return s
    return s[0].upper() + s[1:]

def generate_showcase_file(template_name, template_config, config, dry_run=False):
    """Generate the Showcase.tsx file for a template."""
    component = template_config["component"]
    layouts = template_config["layouts"]
    themes = get_all_themes(config)
    theme_constants = config["themeConstants"]
    
    total = len(themes) * len(layouts)
    
    # Build imports
    original_themes = config["themes"]["original"]
    extended_themes = config["themes"]["extended"]
    european_themes = config["themes"]["european"]
    flat_themes = config["themes"]["flat"]
    canva_themes = config["themes"]["canva"]
    
    lines = []
    lines.append(f'''/**
 * {component} Showcase - All {len(themes)} themes x {len(layouts)} layouts = {total} compositions
 * 
 * THEMES ({len(themes)} total):
 *   Original ({len(original_themes)}): {", ".join(original_themes)}
 *   Extended ({len(extended_themes)}): {", ".join(extended_themes)}
 *   European ({len(european_themes)}): {", ".join(european_themes)}
 *   Flat ({len(flat_themes)}): {", ".join(flat_themes)}
 *   Canva ({len(canva_themes)}): {", ".join(canva_themes)}
 * 
 * LAYOUTS ({len(layouts)}): {", ".join(layouts)}
 * 
 * Auto-generated by scripts/generate-template-variants.py
 */

import React from "react";
import {{ {component} }} from "./{component}";
import type {{ {component}Spec }} from "./{component}";
import {{
  // Original themes
  {", ".join(theme_constants[t] for t in original_themes)},
  // Extended themes
  {", ".join(theme_constants[t] for t in extended_themes)},
  // European themes
  {", ".join(theme_constants[t] for t in european_themes)},
  // Flat themes
  {", ".join(theme_constants[t] for t in flat_themes)},
  // Canva themes
  {", ".join(theme_constants[t] for t in canva_themes)},
  BrandKit,
  applyBrandKit,
}} from "../_shared/themes";
''')
    
    # Add sample spec placeholder
    lines.append(f'''
// ── Sample Data ─────────────────────────────────────────────────
// TODO: Add appropriate sample data for {component}
const SAMPLE_SPEC: {component}Spec = {{
  // Add sample data here
}};
''')
    
    # Generate components by theme group
    for group_name, group_themes in [
        ("ORIGINAL", original_themes),
        ("EXTENDED", extended_themes),
        ("EUROPEAN", european_themes),
        ("FLAT", flat_themes),
        ("CANVA", canva_themes),
    ]:
        group_count = len(group_themes) * len(layouts)
        lines.append(f'''
// {"═" * 66}
// {group_name} THEMES ({len(group_themes)} themes x {len(layouts)} layouts = {group_count} compositions)
// {"═" * 66}
''')
        
        for theme in group_themes:
            theme_pascal = pascal_case(theme)
            theme_const = theme_constants[theme]
            lines.append(f"// {theme_pascal}")
            
            for layout in layouts:
                layout_pascal = pascal_case(layout)
                export_name = f"{component}{theme_pascal}{layout_pascal}"
                lines.append(f'''export const {export_name}: React.FC<{{ brandKit?: BrandKit }}> = ({{ brandKit }}) => (
  <{component} spec={{SAMPLE_SPEC}} theme={{applyBrandKit({theme_const}, brandKit)}} layout="{layout}" format="vertical" />
);''')
            lines.append("")
    
    content = "\n".join(lines)
    
    if dry_run:
        print(f"Would generate: src/remotion/templates/{template_name}/{component}Showcase.tsx")
        print(f"  {total} compositions ({len(themes)} themes x {len(layouts)} layouts)")
        return content
    
    output_path = Path(f"src/remotion/templates/{template_name}/{component}Showcase.tsx")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    print(f"Generated: {output_path}")
    return content

def generate_root_imports(template_name, template_config, config, dry_run=False):
    """Generate Root.tsx import statement and composition registrations."""
    component = template_config["component"]
    layouts = template_config["layouts"]
    themes = get_all_themes(config)
    
    # Generate import names
    imports = []
    for theme in themes:
        theme_pascal = pascal_case(theme)
        for layout in layouts:
            layout_pascal = pascal_case(layout)
            imports.append(f"{component}{theme_pascal}{layout_pascal}")
    
    import_line = f'import {{ {", ".join(imports)} }} from "./templates/{template_name}/{component}Showcase";'
    
    # Generate compositions
    compositions = []
    for theme in themes:
        theme_pascal = pascal_case(theme)
        for layout in layouts:
            layout_pascal = pascal_case(layout)
            comp_name = f"{component}{theme_pascal}{layout_pascal}"
            comp_id = f"{component}-{theme_pascal}{layout_pascal}"
            compositions.append(f'      <Composition id="{comp_id}" component={{{comp_name}}} durationInFrames={{DUR}} fps={{FPS}} width={{1080}} height={{1920}} />')
    
    folder_content = f'''    <Folder name="{component}">
{chr(10).join(compositions)}
    </Folder>'''
    
    if dry_run:
        print(f"\n--- Root.tsx Import ---")
        print(import_line[:200] + "..." if len(import_line) > 200 else import_line)
        print(f"\n--- Root.tsx Folder ({len(compositions)} compositions) ---")
        print(folder_content[:500] + "..." if len(folder_content) > 500 else folder_content)
        return import_line, folder_content
    
    return import_line, folder_content

def generate_templates_json_entry(template_name, template_config, config, dry_run=False):
    """Generate templates.json entry for a template."""
    component = template_config["component"]
    layouts = template_config["layouts"]
    themes = get_all_themes(config)
    
    variants = []
    for theme in themes:
        theme_pascal = pascal_case(theme)
        for layout in layouts:
            layout_pascal = pascal_case(layout)
            variant_id = f"{component}-{theme_pascal}{layout_pascal}"
            variant_name = f"{theme_pascal} {layout_pascal}"
            variants.append({
                "id": variant_id,
                "name": variant_name,
                "style": theme,
                "layout": layout
            })
    
    entry = {
        "slug": template_name,
        "camel": component,
        "name": component,
        "description": template_config.get("description", ""),
        "icon": template_config.get("icon", "file"),
        "color": template_config.get("color", "gray"),
        "primaryVariant": f"{pascal_case(themes[0])}{pascal_case(layouts[0])}",
        "variantCount": len(variants),
        "variants": variants,
        "primaryId": f"{component}-{pascal_case(themes[0])}{pascal_case(layouts[0])}"
    }
    
    if dry_run:
        print(f"\n--- templates.json entry ({len(variants)} variants) ---")
        print(json.dumps(entry, indent=2)[:1000] + "..." if len(json.dumps(entry, indent=2)) > 1000 else json.dumps(entry, indent=2))
        return entry
    
    return entry

def main():
    parser = argparse.ArgumentParser(description="Generate template variants from configuration")
    parser.add_argument("--template", "-t", help="Template name (e.g., listicle)")
    parser.add_argument("--all", "-a", action="store_true", help="Generate for all templates")
    parser.add_argument("--dry-run", "-n", action="store_true", help="Show what would be generated without writing files")
    parser.add_argument("--output", "-o", choices=["showcase", "root", "json", "all"], default="all",
                       help="What to generate: showcase, root, json, or all")
    
    args = parser.parse_args()
    
    if not args.template and not args.all:
        parser.print_help()
        sys.exit(1)
    
    config = load_config()
    
    templates_to_process = []
    if args.all:
        templates_to_process = list(config["templates"].keys())
    else:
        if args.template not in config["templates"]:
            print(f"Error: Template '{args.template}' not found in config")
            print(f"Available templates: {', '.join(config['templates'].keys())}")
            sys.exit(1)
        templates_to_process = [args.template]
    
    for template_name in templates_to_process:
        template_config = config["templates"][template_name]
        print(f"\n{'='*60}")
        print(f"Processing: {template_name}")
        print(f"{'='*60}")
        
        if args.output in ["showcase", "all"]:
            generate_showcase_file(template_name, template_config, config, args.dry_run)
        
        if args.output in ["root", "all"]:
            generate_root_imports(template_name, template_config, config, args.dry_run)
        
        if args.output in ["json", "all"]:
            generate_templates_json_entry(template_name, template_config, config, args.dry_run)

if __name__ == "__main__":
    main()
