/**
 * Composition Type Definitions
 *
 * Core type definitions for dynamically generated Remotion compositions.
 * These types define the structure of composition configs, ID generation,
 * and the relationship between templates, themes, and layouts.
 *
 * @module themes/types/composition
 * @see Requirements: 7.1-7.6, 9.1-9.3
 */

import type { ComponentType } from "react";
import type { z } from "zod";
import type { Theme } from "./theme";
import type { BrandKit } from "./brandkit";

/**
 * Composition configuration interface.
 *
 * A CompositionConfig represents a complete Remotion composition
 * configuration, combining a template with a specific theme and layout.
 * These configs are dynamically generated by the CompositionGenerator.
 *
 * @see Requirements: 7.1-7.6
 */
export interface CompositionConfig {
  // ── Identity ──────────────────────────────────────────────────────
  /**
   * Unique composition identifier in PascalCase format.
   * Generated from template, theme, and layout names.
   * @example "Testimonial-Ocean-Centered"
   * @example "CaseStudy-Dark-Split"
   */
  id: string;

  /**
   * Legacy composition ID for backward compatibility.
   * Used to maintain existing URL patterns after migration.
   * @see Requirements: 9.1-9.3
   */
  legacyId?: string;

  // ── Component ─────────────────────────────────────────────────────
  /**
   * React component that renders this composition.
   * This is the template component with theme and layout pre-configured.
   */
  component: ComponentType<CompositionProps>;

  // ── Dimensions ────────────────────────────────────────────────────
  /**
   * Video width in pixels.
   */
  width: number;

  /**
   * Video height in pixels.
   */
  height: number;

  /**
   * Frames per second.
   */
  fps: number;

  /**
   * Total duration in frames.
   */
  durationInFrames: number;

  // ── Props ─────────────────────────────────────────────────────────
  /**
   * Default props passed to the composition component.
   * Contains the theme, layout, spec data, and optional BrandKit.
   */
  defaultProps: CompositionDefaultProps;

  // ── Schema ────────────────────────────────────────────────────────
  /**
   * Zod schema for Remotion Studio prop editing.
   * Enables type-safe prop editing in the Remotion Studio UI.
   */
  schema?: z.ZodType<CompositionProps>;

  // ── Metadata ──────────────────────────────────────────────────────
  /**
   * ID of the template this composition is based on.
   * @example "testimonial", "case-study"
   */
  templateId: string;

  /**
   * Name of the theme applied to this composition.
   * @example "ocean", "dark", "corporate"
   */
  themeName: string;

  /**
   * Name of the layout variant used.
   * @example "centered", "split", "editorial"
   */
  layoutName: string;
}

/**
 * Default props for a composition.
 *
 * These props are passed to the composition component when rendered.
 * They include the theme configuration, layout selection, and content data.
 */
export interface CompositionDefaultProps {
  /**
   * The theme to apply to the composition.
   */
  theme: Theme;

  /**
   * The layout variant to render.
   */
  layout: string;

  /**
   * The specification data for the composition content.
   */
  spec: Record<string, unknown>;

  /**
   * Optional brand kit for custom color overrides.
   */
  brandKit?: BrandKit;
}

/**
 * Props interface for composition components.
 *
 * This extends CompositionDefaultProps with any additional
 * props that may be passed at render time.
 */
export interface CompositionProps extends CompositionDefaultProps {
  /**
   * Additional props can be passed through.
   */
  [key: string]: unknown;
}

// ═══════════════════════════════════════════════════════════════════════════
// Composition ID Generation Types
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Components used to generate a composition ID.
 *
 * A composition ID is generated from the combination of
 * template, theme, and layout names in PascalCase format.
 *
 * @see Requirements: 7.4-7.6, 18.1-18.3
 */
export interface CompositionIdComponents {
  /**
   * Template identifier (will be converted to PascalCase).
   * @example "testimonial" → "Testimonial"
   */
  templateId: string;

  /**
   * Theme name (will be converted to PascalCase).
   * @example "ocean" → "Ocean"
   */
  themeName: string;

  /**
   * Layout name (will be converted to PascalCase).
   * @example "centered" → "Centered"
   */
  layoutName: string;
}

/**
 * Result of composition ID generation.
 *
 * Contains the generated ID and any uniqueness suffix applied.
 */
export interface CompositionIdResult {
  /**
   * The generated composition ID.
   * @example "Testimonial-Ocean-Centered"
   */
  id: string;

  /**
   * The base ID before any uniqueness suffix was applied.
   * @example "Testimonial-Ocean-Centered"
   */
  baseId: string;

  /**
   * Numeric suffix applied for uniqueness (if any).
   * Undefined if no suffix was needed.
   * @example 2, 3, etc.
   */
  suffix?: number;

  /**
   * Whether a suffix was applied to ensure uniqueness.
   */
  isUnique: boolean;
}

/**
 * Options for composition ID generation.
 */
export interface CompositionIdOptions {
  /**
   * Set of already-used IDs to check for conflicts.
   */
  usedIds?: Set<string>;

  /**
   * Whether to automatically append a suffix for uniqueness.
   * @default true
   */
  ensureUnique?: boolean;

  /**
   * Custom separator between ID components.
   * @default "-"
   */
  separator?: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// Composition Generation Types
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Options for composition generation.
 *
 * These options control how compositions are generated
 * from template and theme registries.
 */
export interface CompositionGenerationOptions {
  /**
   * Default duration in frames for generated compositions.
   * Can be overridden by template-specific settings.
   */
  defaultDurationInFrames?: number;

  /**
   * Default FPS for generated compositions.
   * Can be overridden by template-specific settings.
   */
  defaultFps?: number;

  /**
   * Default width for generated compositions.
   * Can be overridden by template-specific settings.
   */
  defaultWidth?: number;

  /**
   * Default height for generated compositions.
   * Can be overridden by template-specific settings.
   */
  defaultHeight?: number;

  /**
   * Whether to skip orphaned templates (no implementation).
   * @default true
   */
  skipOrphaned?: boolean;

  /**
   * Whether to include legacy IDs for backward compatibility.
   * @default true
   */
  includeLegacyIds?: boolean;

  /**
   * Filter to specific template IDs.
   * If provided, only these templates will be processed.
   */
  templateFilter?: string[];

  /**
   * Filter to specific theme names.
   * If provided, only these themes will be used.
   */
  themeFilter?: string[];
}

/**
 * Result of composition generation.
 *
 * Contains the generated compositions and metadata about
 * the generation process.
 */
export interface CompositionGenerationResult {
  /**
   * Array of generated composition configurations.
   */
  compositions: CompositionConfig[];

  /**
   * Number of templates processed.
   */
  templatesProcessed: number;

  /**
   * Number of templates skipped (orphaned or filtered).
   */
  templatesSkipped: number;

  /**
   * Number of themes used.
   */
  themesUsed: number;

  /**
   * IDs of orphaned templates that were skipped.
   */
  orphanedTemplates: string[];

  /**
   * Any warnings generated during the process.
   */
  warnings: string[];
}

// ═══════════════════════════════════════════════════════════════════════════
// Utility Functions
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Converts a string to PascalCase.
 *
 * Used for generating composition IDs from kebab-case
 * template IDs and theme names.
 *
 * @param str - The string to convert
 * @returns The string in PascalCase
 *
 * @example
 * toPascalCase("testimonial") // "Testimonial"
 * toPascalCase("case-study") // "CaseStudy"
 * toPascalCase("game-day-intro") // "GameDayIntro"
 */
export function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

/**
 * Generates a composition ID from its components.
 *
 * Creates a PascalCase ID in the format "Template-Theme-Layout".
 * Optionally ensures uniqueness by appending a numeric suffix.
 *
 * @param components - The template, theme, and layout identifiers
 * @param options - Options for ID generation
 * @returns The generated ID result
 *
 * @see Requirements: 7.4-7.6, 18.1-18.3
 *
 * @example
 * generateCompositionId(
 *   { templateId: "testimonial", themeName: "ocean", layoutName: "centered" }
 * )
 * // { id: "Testimonial-Ocean-Centered", baseId: "Testimonial-Ocean-Centered", isUnique: true }
 */
export function generateCompositionId(
  components: CompositionIdComponents,
  options: CompositionIdOptions = {}
): CompositionIdResult {
  const { usedIds, ensureUnique = true, separator = "-" } = options;

  const templatePascal = toPascalCase(components.templateId);
  const themePascal = toPascalCase(components.themeName);
  const layoutPascal = toPascalCase(components.layoutName);

  const baseId = `${templatePascal}${separator}${themePascal}${separator}${layoutPascal}`;

  // If no uniqueness check needed or no used IDs provided
  if (!ensureUnique || !usedIds || !usedIds.has(baseId)) {
    return {
      id: baseId,
      baseId,
      isUnique: true,
    };
  }

  // Find a unique ID by appending a numeric suffix
  let suffix = 2;
  let candidateId = `${baseId}${separator}${suffix}`;

  while (usedIds.has(candidateId)) {
    suffix++;
    candidateId = `${baseId}${separator}${suffix}`;
  }

  return {
    id: candidateId,
    baseId,
    suffix,
    isUnique: true,
  };
}

/**
 * Parses a composition ID into its components.
 *
 * Extracts the template, theme, and layout from a composition ID.
 * Returns undefined if the ID format is invalid.
 *
 * @param id - The composition ID to parse
 * @returns The parsed components or undefined if invalid
 *
 * @example
 * parseCompositionId("Testimonial-Ocean-Centered")
 * // { templateId: "testimonial", themeName: "ocean", layoutName: "centered" }
 */
export function parseCompositionId(
  id: string
): CompositionIdComponents | undefined {
  const parts = id.split("-");

  // Must have at least 3 parts: Template-Theme-Layout
  if (parts.length < 3) {
    return undefined;
  }

  // Handle IDs with numeric suffix (e.g., "Testimonial-Ocean-Centered-2")
  const lastPart = parts[parts.length - 1];
  const hasNumericSuffix = /^\d+$/.test(lastPart);

  if (hasNumericSuffix && parts.length < 4) {
    return undefined;
  }

  const effectiveParts = hasNumericSuffix ? parts.slice(0, -1) : parts;

  // For now, assume simple format: Template-Theme-Layout
  // More complex templates with hyphens would need special handling
  if (effectiveParts.length === 3) {
    return {
      templateId: effectiveParts[0].toLowerCase(),
      themeName: effectiveParts[1].toLowerCase(),
      layoutName: effectiveParts[2].toLowerCase(),
    };
  }

  // Handle multi-word components (e.g., "CaseStudy-MaterialBlue-FullWidth")
  // This is a simplified parser - complex cases may need template registry lookup
  return {
    templateId: effectiveParts[0].toLowerCase(),
    themeName: effectiveParts[1].toLowerCase(),
    layoutName: effectiveParts.slice(2).join("-").toLowerCase(),
  };
}

/**
 * Validates a composition ID format.
 *
 * Checks that the ID follows the expected PascalCase format
 * with hyphen separators.
 *
 * @param id - The composition ID to validate
 * @returns True if the ID format is valid
 */
export function isValidCompositionId(id: string): boolean {
  // Must have at least 3 parts separated by hyphens
  const parts = id.split("-");
  if (parts.length < 3) {
    return false;
  }

  // Each part must start with an uppercase letter (PascalCase)
  // or be a numeric suffix
  return parts.every((part, index) => {
    // Allow numeric suffix as last part
    if (index === parts.length - 1 && /^\d+$/.test(part)) {
      return true;
    }
    // Must start with uppercase letter
    return /^[A-Z][a-zA-Z0-9]*$/.test(part);
  });
}
